In [1]:
import numpy as np
import pandas as pd

In [2]:
array_1d = np.array([1, 2, 3, 4, 5])

array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

array_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("1D array:")
print(array_1d)
print("Shape:", array_1d.shape)

print("\n2D array:")
print(array_2d)
print("Shape:", array_2d.shape)

print("\n3D array:")
print(array_3d)
print("Shape:", array_3d.shape)

1D array:
[1 2 3 4 5]
Shape: (5,)

2D array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)


In [3]:
array = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

addition = array + 5

print("Original array:")
print(array)

print("\nAfter broadcasting:")
print(addition)

Original array:
[[10 20 30]
 [40 50 60]]

After broadcasting:
[[15 25 35]
 [45 55 65]]


In [4]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

addition = a + b
multiplication = a * b
square = a ** 2

print("Addition:", addition)
print("Multiplication:", multiplication)
print("Square:", square)

Addition: [11 22 33 44 55]
Multiplication: [ 10  40  90 160 250]
Square: [ 1  4  9 16 25]


In [5]:
matrix_a = np.array([
    [1, 2],
    [3, 4]
])

matrix_b = np.array([
    [5, 6],
    [7, 8]
])

result = matrix_a @ matrix_b

print("Matrix A:")
print(matrix_a)

print("\nMatrix B:")
print(matrix_b)

print("\nMatrix multiplication result:")
print(result)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Matrix multiplication result:
[[19 22]
 [43 50]]


In [6]:
from pathlib import Path

csv_files = list(Path(".").rglob("*.csv"))

print("CSV files found:")
for file in csv_files:
    print(file)

print("\nTotal CSV files:", len(csv_files))

CSV files found:
docs\getting-started\data_quality_alerts.csv
docs\features\tables\config_html.csv
docs\advanced_settings\tables\config_correlations.csv
docs\advanced_settings\tables\config_general.csv
docs\advanced_settings\tables\config_html.csv
docs\advanced_settings\tables\config_interactions.csv
docs\advanced_settings\tables\config_missing.csv
docs\advanced_settings\tables\config_variables.csv
docs\advanced_settings\tables\corr_matrices.csv

Total CSV files: 9


In [7]:
import numpy as np
import pandas as pd

file_path = "docs/getting-started/data_quality_alerts.csv"

df = pd.read_csv(file_path)

print("Dataset shape:", df.shape)
print("\nFirst 5 rows:")
print(df.head())

print("\nColumn names:")
print(df.columns.tolist())

# Select numeric columns
numeric_df = df.select_dtypes(include=np.number)

print("\nNumeric columns:")
print(numeric_df.columns.tolist())

# Mean using NumPy
mean_values = np.mean(numeric_df, axis=0)

# Standard deviation using NumPy
std_values = np.std(numeric_df, axis=0)

# Correlation using NumPy
correlation_matrix = np.corrcoef(numeric_df.T)

print("\nMean:")
print(mean_values)

print("\nStandard Deviation:")
print(std_values)

print("\nCorrelation Matrix:")
print(correlation_matrix)

Dataset shape: (18, 2)

First 5 rows:
              **Alert**                                    **Description**
0          ``Constant``                     Column only contains one value
1             ``Zeros``                         Column only contains zeros
2  ``High Correlation``  Correlations (either Spearman, Cramer, Pearson...
3  ``High Cardinality``  Whether the column has more than 50 distinct v...
4         ``Imbalance``  Column is highly imbalanced. Threshold is conf...

Column names:
['**Alert**', '**Description**']

Numeric columns:
[]

Mean:
Series([], dtype: float64)

Standard Deviation:
Series([], dtype: float64)

Correlation Matrix:
[]


In [8]:
from pathlib import Path
import pandas as pd

csv_files = list(Path(".").rglob("*.csv"))

for file in csv_files:
    try:
        df_check = pd.read_csv(file)

        numeric_columns = df_check.select_dtypes(include="number").columns.tolist()

        print("=" * 70)
        print("File:", file)
        print("Shape:", df_check.shape)
        print("Numeric columns:", numeric_columns)

    except Exception as e:
        print("Could not read:", file)
        print("Error:", e)

File: docs\getting-started\data_quality_alerts.csv
Shape: (18, 2)
Numeric columns: []
File: docs\features\tables\config_html.csv
Shape: (8, 4)
Numeric columns: []
File: docs\advanced_settings\tables\config_correlations.csv
Shape: (18, 4)
Numeric columns: []
File: docs\advanced_settings\tables\config_general.csv
Shape: (3, 4)
Numeric columns: []
File: docs\advanced_settings\tables\config_html.csv
Shape: (8, 4)
Numeric columns: []
File: docs\advanced_settings\tables\config_interactions.csv
Shape: (2, 4)
Numeric columns: []
File: docs\advanced_settings\tables\config_missing.csv
Shape: (3, 4)
Numeric columns: []
File: docs\advanced_settings\tables\config_variables.csv
Shape: (15, 4)
Numeric columns: []
File: docs\advanced_settings\tables\corr_matrices.csv
Shape: (6, 2)
Numeric columns: []


In [9]:
import numpy as np
import pandas as pd

# Real Iris CSV dataset
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

df_iris = pd.read_csv(url)

print("Dataset shape:", df_iris.shape)

print("\nFirst 5 rows:")
print(df_iris.head())

# Select numeric columns
numeric_data = df_iris.select_dtypes(include=np.number)

print("\nNumeric columns:")
print(numeric_data.columns.tolist())

# NumPy calculations
mean_values = np.mean(numeric_data, axis=0)
std_values = np.std(numeric_data, axis=0)
correlation_matrix = np.corrcoef(numeric_data.T)

print("\nMean:")
for column, value in zip(numeric_data.columns, mean_values):
    print(f"{column}: {value:.4f}")

print("\nStandard Deviation:")
for column, value in zip(numeric_data.columns, std_values):
    print(f"{column}: {value:.4f}")

print("\nCorrelation Matrix:")
print(pd.DataFrame(
    correlation_matrix,
    index=numeric_data.columns,
    columns=numeric_data.columns
))

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1082)>

In [10]:
import numpy as np
import pandas as pd

# Load the real CSV dataset
df_iris = pd.read_csv("iris.csv")

print("Dataset shape:", df_iris.shape)

print("\nFirst 5 rows:")
print(df_iris.head())

# Select numeric columns
numeric_data = df_iris.select_dtypes(include=np.number)

print("\nNumeric columns:")
print(numeric_data.columns.tolist())

# Calculate statistics using NumPy
mean_values = np.mean(numeric_data, axis=0)
std_values = np.std(numeric_data, axis=0)
correlation_matrix = np.corrcoef(numeric_data.T)

print("\nMean:")
print(mean_values)

print("\nStandard Deviation:")
print(std_values)

print("\nCorrelation Matrix:")
print(pd.DataFrame(
    correlation_matrix,
    index=numeric_data.columns,
    columns=numeric_data.columns
))

FileNotFoundError: [Errno 2] No such file or directory: 'iris.csv'

In [11]:
import numpy as np
import pandas as pd

# Create a CSV file containing the real Iris dataset
iris_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

# Try downloading using pandas
try:
    iris_df = pd.read_csv(iris_url)
    iris_df.to_csv("iris.csv", index=False)
    print("iris.csv created successfully.")

except Exception as e:
    print("Could not download the dataset.")
    print("Error:", e)

Could not download the dataset.
Error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1082)>


In [12]:
import os

print("Jupyter working directory:")
print(os.getcwd())

print("\nFiles in this folder:")
print(os.listdir())

Jupyter working directory:
C:\Users\Varsh\fg-data-profiling

Files in this folder:
['.devcontainer', '.git', '.github', '.gitignore', '.ipynb_checkpoints', '.pre-commit-config.yaml', '.releaserc.json', 'commitlint.config.cjs', 'CONTRIBUTING.md', 'docs', 'examples', 'install.bat', 'iris.txt', 'LICENSE', 'make.bat', 'Makefile', 'MANIFEST.in', 'mkdocs.yml', 'pyproject.toml', 'README.md', 'renovate.json', 'setup.py', 'src', 'tests', 'venv', 'W1D1_Numpy_Fundamentals.ipynb']


In [13]:
import pandas as pd

iris_file = "iris.txt"

iris_df = pd.read_csv(iris_file)

print("Dataset shape:", iris_df.shape)

print("\nFirst 5 rows:")
print(iris_df.head())

print("\nColumn names:")
print(iris_df.columns.tolist())

Dataset shape: (150, 5)

First 5 rows:
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Column names:
['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']


In [14]:
import numpy as np
import pandas as pd

# Load the real Iris dataset
iris_df = pd.read_csv("iris.txt")

# Select only numeric columns
numeric_data = iris_df.select_dtypes(include=np.number)

print("Numeric columns:")
print(numeric_data.columns.tolist())

# Calculate mean using NumPy
mean_values = np.mean(numeric_data, axis=0)

# Calculate standard deviation using NumPy
std_values = np.std(numeric_data, axis=0)

# Calculate correlation using NumPy
correlation_matrix = np.corrcoef(numeric_data.T)

# Display mean
print("\nMean:")
for column, value in zip(numeric_data.columns, mean_values):
    print(f"{column}: {value:.4f}")

# Display standard deviation
print("\nStandard Deviation:")
for column, value in zip(numeric_data.columns, std_values):
    print(f"{column}: {value:.4f}")

# Display correlation matrix
print("\nCorrelation Matrix:")
correlation_df = pd.DataFrame(
    correlation_matrix,
    index=numeric_data.columns,
    columns=numeric_data.columns
)
print(correlation_df.round(4))

Numeric columns:
['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

Mean:
sepal_length: 5.8433
sepal_width: 3.0573
petal_length: 3.7580
petal_width: 1.1993

Standard Deviation:
sepal_length: 0.8253
sepal_width: 0.4344
petal_length: 1.7594
petal_width: 0.7597

Correlation Matrix:
              sepal_length  sepal_width  petal_length  petal_width
sepal_length        1.0000      -0.1176        0.8718       0.8179
sepal_width        -0.1176       1.0000       -0.4284      -0.3661
petal_length        0.8718      -0.4284        1.0000       0.9629
petal_width         0.8179      -0.3661        0.9629       1.0000


## W1D1 Self-Review Checklist

- [x] NumPy installed and imported successfully
- [x] Created 1D, 2D, and 3D NumPy arrays
- [x] Verified array shapes
- [x] Performed broadcasting
- [x] Performed vectorized operations without Python loops
- [x] Performed matrix multiplication
- [x] Loaded a real Iris dataset
- [x] Calculated mean using NumPy
- [x] Calculated standard deviation using NumPy
- [x] Calculated correlation using NumPy
- [x] Outputs verified in the notebook

## Conclusion

NumPy was used to create and manipulate multidimensional arrays,
perform broadcasting and vectorized operations, perform matrix
multiplication, and calculate statistical measures such as mean,
standard deviation, and correlation on a real dataset.

